package br.com.fiap.movies.repository

import br.com.fiap.movies.model.Movie

class MovieRepository {
    companion object {
        val movieList = listOf(
            Movie("Harry Potter", "Harry Potter é um jovem comum de 11 anos até que recebe uma carta para estudar na Escola de Magia e Bruxaria de Hogwarts, onde ele descobre ser, na verdade, um bruxo. Nela, o garoto conquista a amizade de Hagrid, além de Hermione e Ron. No entanto, ele descobre ter um grande inimigo, o terrível Voldemort", "12+", "Aventura", "1h30m", true),
            Movie("Senhor dos Aneis", "Numa terra fantástica e única, chamada Terra-Média, um hobbit (seres de estatura entre 80 cm e 1,20 m, com pés peludos e bochechas um pouco avermelhadas) recebe de presente de seu tio o Um Anel, um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso o hobbit Frodo (Elijah Woods) terá um caminho árduo pela frente, onde encontrará perigo, medo e personagens bizarros. Ao seu lado para o cumprimento desta jornada aos poucos ele poderá contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando 9 pessoas que formarão a Sociedade do Anel.", "12+", "Ação", "1h30m", true),
            Movie("Missão Impossivel", "Após evitar que armas de gás fossem vendidas a terroristas chechenos, o agente da IMF (ou Força Missão Impossível) Ethan Hunt é capturado por um grupo terrorista de agentes espiões de vários países que foram dados como mortos, chamado Sindicato, e consegue fugir graças a ajuda de uma mulher misteriosa.", "18+", "Ação", "1h30m", true),
            Movie("Space Jam", "Após uma reunião na sede da Warner studios Lebron James e seu filho são sequestrados para dentro do mundo virtual e disputam uma partida de basquete valendo a volta para o mundo real, mas principalmente para fortalecer os laços familiares Primeiramente lançado em 1996, o filme original foi um sucesso.", "12+", "Animação", "1h30m", false),
            Movie("John Wick", "John Wick (Keanu Reeves) já foi um dos assassinos mais temidos da cidade de Nova York, trabalhando em parceria com a máfia russa. Um dia, ele decide se aposentar, e neste período tem que lidar com a triste morte de sua esposa. Vítima de uma doença grave, ela já previa a sua própria morte, e deu de presente ao marido um cachorro para cuidar em seu período de luto. No entanto, poucos dias após o funeral, o cachorro é morto por ladrões que roubam o seu carro. John Wick parte em busca de vingança contra estes homens que ele já conhecia muito bem, e que roubaram o último símbolo da mulher que ele amava.", "18+", "Ação", "1h30m", false),
            Movie("Shazam", "John Wick (Keanu Reeves) já foi um dos assassinos mais temidos da cidade de Nova York, trabalhando em parceria com a máfia russa. Um dia, ele decide se aposentar, e neste período tem que lidar com a triste morte de sua esposa. Vítima de uma doença grave, ela já previa a sua própria morte, e deu de presente ao marido um cachorro para cuidar em seu período de luto. No entanto, poucos dias após o funeral, o cachorro é morto por ladrões que roubam o seu carro. John Wick parte em busca de vingança contra estes homens que ele já conhecia muito bem, e que roubaram o último símbolo da mulher que ele amava.", "12+", "Aventura", "2h38m", true),
            Movie("Jack Reacher - O Ultimo Tiro", "Jack Reacher, um ex-investigador militar, é convocado para resolver o misterioso caso de um atirador que matou cinco pessoas aleatórias em Indiana. Depois de ser agredido em um bar, ele suspeita que alguém esteja tentando impedir sua investigação.", "12+", "Ação", "1h50m", true),
            Movie("Ray", "Ray Charles se tornou um dos maiores gênios musicais do século 20. Deficiente visual desde a infância, ele sobressaiu por conta de uma combinação incomum entre audácia e talento. Mas sua vida também teve excessos.", "12+", "Musical", "1h", false)

        )    }
}
